### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by LockBell** [PersesTitan/OTLanguage#14]
When using an array, using ',' causes the array to be split in an undesirable way.

**Comment by PersesTitan** [comment]
The String Non-Tokenization principle makes it difficult to distinguish tokens, so come up with other alternative methods.

**Comment by LockBell** [comment]
> String Non-Tokenization 원칙은 토큰을 구별하기 어렵게 하므로 다른 대체 방법을 생각해 보십시오.
